config/routes.rb
Rails.application.routes.draw do
  resources :cryptocurrencies
  devise_for :users
  #get 'home/index'
  root 'home#index'
  get	'home/about'
  get	'home/lookup'
  post 'home/lookup'	=>	'home/lookup'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cryptocurrency.rb
class Cryptocurrency < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :cryptocurrencies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cryptocurrencies_controller.rb
class CryptocurrenciesController < ApplicationController
  before_action :set_cryptocurrency, only: [:show, :edit, :update, :destroy]
  # this authenticate user before doing anything from this controller
  before_action :authenticate_user!
  # show the correct pages to the correct users
  before_action :correct_user, only: [:show, :edit, :update, :destory]
  # GET /cryptocurrencies
  # GET /cryptocurrencies.json
  def index
    @cryptocurrencies = Cryptocurrency.all
  end

  # GET /cryptocurrencies/1
  # GET /cryptocurrencies/1.json
  def show
  end

  # GET /cryptocurrencies/new
  def new
    @cryptocurrency = Cryptocurrency.new
  end

  # GET /cryptocurrencies/1/edit
  def edit
  end

  # POST /cryptocurrencies
  # POST /cryptocurrencies.json
  def create
    @cryptocurrency = Cryptocurrency.new(cryptocurrency_params)

    respond_to do |format|
      if @cryptocurrency.save
        format.html { redirect_to @cryptocurrency, notice: 'Cryptocurrency was successfully created.' }
        format.json { render :show, status: :created, location: @cryptocurrency }
      else
        format.html { render :new }
        format.json { render json: @cryptocurrency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cryptocurrencies/1
  # PATCH/PUT /cryptocurrencies/1.json
  def update
    respond_to do |format|
      if @cryptocurrency.update(cryptocurrency_params)
        format.html { redirect_to @cryptocurrency, notice: 'Cryptocurrency was successfully updated.' }
        format.json { render :show, status: :ok, location: @cryptocurrency }
      else
        format.html { render :edit }
        format.json { render json: @cryptocurrency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cryptocurrencies/1
  # DELETE /cryptocurrencies/1.json
  def destroy
    @cryptocurrency.destroy
    respond_to do |format|
      format.html { redirect_to cryptocurrencies_url, notice: 'Cryptocurrency was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cryptocurrency
      @cryptocurrency = Cryptocurrency.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cryptocurrency_params
      params.require(:cryptocurrency).permit(:symbol, :user_id, :cost_per, :amount_owned)
    end

    def correct_user
      @correct = current_user.cryptocurrencies.find_by(id: params[:id])
      redirect_to cryptocurrencies_path, notice: 'You are not autherized to access that page' if @correct.nil?
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	require 'net/http'
  	require 'json'
  	@url = 'https://api.coinmarketcap.com/v2/ticker/'
  	@uri = URI(@url)
  	@response = Net::HTTP.get(@uri)
  	@coins = JSON.parse(@response)
  	@my_coins = ['BTC', 'XRP','XLM','SC']
  end

  def about
  end

  def lookup

  	require 'net/http'
  	require 'json'
  	@url = 'https://api.coinmarketcap.com/v2/ticker/'
  	@uri = URI(@url)
  	@response = Net::HTTP.get(@uri)
  	@lookup_coins = JSON.parse(@response)

  	@symbol = params[:sym]
  	if @symbol
  		@symbol = @symbol.upcase
  	end
  	if @symbol == ""
  		@symbol = "Please enter a currency symbol!"
  	end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cryptocurrencies_helper.rb
module CryptocurrenciesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cryptocurrencies/_form.html.erb
<%= form_with(model: cryptocurrency, local: true) do |form| %>
  <% if cryptocurrency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cryptocurrency.errors.count, "error") %> prohibited this cryptocurrency from being saved:</h2>

      <ul>
      <% cryptocurrency.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :symbol %>
    <%= form.text_field :symbol, id: :cryptocurrency_symbol %>
  </div>

  <div class="field">
    <%= form.number_field :user_id, id: :cryptocurrency_user_id, value: current_user.id, type: "hidden" %>
  </div>

  <div class="field">
    <%= form.label :cost_per %>
    <%= form.text_field :cost_per, id: :cryptocurrency_cost_per %>
  </div>

  <div class="field">
    <%= form.label :amount_owned %>
    <%= form.text_field :amount_owned, id: :cryptocurrency_amount_owned %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cryptocurrencies/edit.html.erb
<h1>Editing Cryptocurrency</h1>

<%= render 'form', cryptocurrency: @cryptocurrency %>

<%= link_to 'Show', @cryptocurrency %> |
<%= link_to 'Back', cryptocurrencies_path %>

app/views/cryptocurrencies/index.html.erb
<h1>Cryptocurrencies</h1>

<table>
  <thead>
    <tr>
      <th>Symbol</th>
      <th>Cost per</th>
      <th>Amount owned</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cryptocurrencies.each do |cryptocurrency| %>
        <% if cryptocurrency.user_id == current_user.id %>
            <tr>
              <td><%= cryptocurrency.symbol %></td>
              <td><%= cryptocurrency.cost_per %></td>
              <td><%= cryptocurrency.amount_owned %></td>
              <td><%= link_to 'Show', cryptocurrency %></td>
              <td><%= link_to 'Edit', edit_cryptocurrency_path(cryptocurrency) %></td>
              <td><%= link_to 'Destroy', cryptocurrency, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
        <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cryptocurrency', new_cryptocurrency_path %>

app/views/cryptocurrencies/new.html.erb
<h1>New Cryptocurrency</h1>

<%= render 'form', cryptocurrency: @cryptocurrency %>

<%= link_to 'Back', cryptocurrencies_path %>

app/views/cryptocurrencies/show.html.erb
<p>
  <strong>Symbol:</strong>
  <%= @cryptocurrency.symbol %>
</p>

<p>
  <strong>User:</strong>
  <%= @cryptocurrency.user_id %>
</p>

<p>
  <strong>Cost per:</strong>
  <%= @cryptocurrency.cost_per %>
</p>

<p>
  <strong>Amount owned:</strong>
  <%= @cryptocurrency.amount_owned %>
</p>

<%= link_to 'Edit', edit_cryptocurrency_path(@cryptocurrency) %> |
<%= link_to 'Back', cryptocurrencies_path %>

app/views/home/_flash.html.erb
<% flash.each do |name,msg| %>
	<div class="alert alert-warning alert-dismissible">
		<button class="close" data-dismiss="alert">
			<i class="glyphicon glyphicon-remove-circle"></i>
		</button>
		<%= content_tag(:div, msg)%>
	</div>
<% end %>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Crypto Portfolio", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About us", home_about_path %></li>
        <li><%= link_to "Lookup", home_lookup_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "All Currencies", cryptocurrencies_path %></li>
          <li><%= link_to "Add Currency", new_cryptocurrency_path %></li>
          <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
          <li><%= link_to "Log Out", destroy_user_session_path, :method => 'delete' %></li>
        <% else %>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Log In", new_user_session_path %></li>
        <% end %>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/home/about.html.erb
<h1>About Us</h1>
<p>This is about us page</p>

app/views/home/index.html.erb
<h1>Hello World!</h1>
<p>This is my first Rails App</p>
<br><br>


<% for x in @coins['data'] %>
	<% for coin in @my_coins %>
		<% if coin == x[1]['symbol'] %>
			<%= x[1]['name'] %> : <%= x[1]['quotes']['USD']['price'] %><br>
			Rank: <%= x[1]['rank'] %><br><br>
		<% end %>
	<% end %>
<% end %>

app/views/home/lookup.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Crypto Curruncy Lookup</h3>
  </div>
  <div class="panel-body">

<%= form_tag home_lookup_path, :method => 'POST', :class => 'form-inline' do %>
	<%= text_field_tag 'sym', nil, placeholder: 'Enter crypto symbol', size: 50, :class => 'form-control' %>
	<%= submit_tag 'Lookup Qoute', :class => 'btn btn-primary' %>
<% end %>

</div>
</div>

<% if @symbol %>
	<% for coin in @lookup_coins['data'] %>
		<% if @symbol == coin[1]['symbol'] %>
			<%= coin[1]['name'] %> : <%= coin[1]['quotes']['USD']['price'] %><br>
			Rank: <%= coin[1]['rank'] %>
		<% end %>
	<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crypto</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
  	<%= render 'home/navbar' %>
  	<div class="container">
      <%= render 'home/flash' %>
    	<%= yield %>
	</div>
  </body>
</html>